// Temporary type stubs for packages declared in package.json that have not yet
// been installed (run `pnpm install` to replace these with real types).

declare module "posthog-js" {
  interface PostHog {
    capture(event: string, properties?: Record<string, unknown>): void;
    identify(distinctId: string, properties?: Record<string, unknown>): void;
  }
  const posthog: PostHog;
  export default posthog;
}

declare module "jszip" {
  interface JSZipObject {
    async(type: "blob"): Promise<Blob>;
  }
  interface JSZip {
    file(name: string, data: string, options?: { base64?: boolean }): this;
    generateAsync(options: { type: "blob" | "arraybuffer" | "uint8array" }): Promise<Blob>;
  }
  interface JSZipStatic {
    new(): JSZip;
  }
  const JSZip: JSZipStatic;
  export default JSZip;
}

// The Wasm build artifact is generated by `cd apps/pdf-wasm && ./build.sh`.
// Until the binary is built, this stub keeps the worker compilable.
declare module "/wasm/pdf_wasm.js" {
  export default function init(wasmUrl: URL | string): Promise<void>;
  export function parse_pdf(data: Uint8Array): unknown;
}
