#!/usr/bin/env bash
# =============================================================================
# OLPDF API — Blue/Green Zero-Downtime Deploy
# =============================================================================
# Usage:
#   ./deploy.sh              # full blue/green deploy
#   ./deploy.sh --rollback   # instantly revert to previous stack
#   ./deploy.sh --status     # show which stack is active
#   ./deploy.sh --logs       # deploy then tail logs
# =============================================================================
set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$APP_DIR/repo"
STATE_FILE="$APP_DIR/.deploy-state"
ENV_FILE="$APP_DIR/.env.prod"
BLUE_PORT=8001
GREEN_PORT=8003   # 8002 is reserved for the Go export-service
HEALTH_RETRIES=24     # 24 × 5s = 2 min max
HEALTH_INTERVAL=5

ROLLBACK=false
TAIL_LOGS=false
STATUS_ONLY=false

for arg in "$@"; do
  case "$arg" in
    --rollback) ROLLBACK=true ;;
    --logs)     TAIL_LOGS=true ;;
    --status)   STATUS_ONLY=true ;;
  esac
done

cd "$APP_DIR"

# ── Helpers ───────────────────────────────────────────────────────────────────
active_stack()   { [ -f "$STATE_FILE" ] && cat "$STATE_FILE" || echo "blue"; }
inactive_stack() { [ "$(active_stack)" = "blue" ] && echo "green" || echo "blue"; }
stack_port()     { [ "$1" = "blue" ] && echo "$BLUE_PORT" || echo "$GREEN_PORT"; }

health_check() {
  local port="$1"
  echo "    Checking http://localhost:$port/health"
  for i in $(seq 1 $HEALTH_RETRIES); do
    if curl -sf "http://localhost:$port/health" >/dev/null 2>&1; then
      echo "    ✓ API healthy!"
      return 0
    fi
    echo "    Attempt $i/$HEALTH_RETRIES — waiting ${HEALTH_INTERVAL}s..."
    sleep "$HEALTH_INTERVAL"
  done
  return 1
}

update_nginx() {
  local stack="$1"
  echo "    Writing upstreams → $stack"
  cat > "$APP_DIR/deploy/nginx/conf.d/upstreams.conf" <<EOF
upstream olpdf_api_upstream {
    server olpdf-api-${stack}:8000 max_fails=3 fail_timeout=30s;
    keepalive 32;
}
EOF
  docker exec olpdf-nginx nginx -t -q && docker exec olpdf-nginx nginx -s reload
  echo "    ✓ Nginx reloaded → $stack"
}

generate_compose() {
  local stack="$1"
  local port
  port=$(stack_port "$stack")
  cat > "$APP_DIR/docker-compose.${stack}.yml" <<COMPOSE
# Auto-generated by deploy.sh — do not edit
services:
  api:
    image: olpdf/api:${stack}
    container_name: olpdf-api-${stack}
    restart: unless-stopped
    ports:
      - "${port}:8000"
    env_file: ${ENV_FILE}
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /app
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/health || exit 1"]
      interval: 20s
      timeout: 7s
      retries: 10
      start_period: 30s
    networks:
      app:
      shared:
        aliases:
          - olpdf-api-${stack}

networks:
  app:
    name: olpdf-app-${stack}
  shared:
    external: true
    name: olpdf-shared
COMPOSE
}

# ── Status ────────────────────────────────────────────────────────────────────
if [ "$STATUS_ONLY" = true ]; then
  ACTIVE=$(active_stack)
  INACTIVE=$(inactive_stack)
  echo "Active:   $ACTIVE  (port: $(stack_port "$ACTIVE"))"
  echo "Inactive: $INACTIVE (port: $(stack_port "$INACTIVE"))"
  echo ""
  echo "=== $ACTIVE containers ==="
  docker compose -p "olpdf-$ACTIVE" -f "$APP_DIR/docker-compose.$ACTIVE.yml" ps 2>/dev/null || echo "(not running)"
  exit 0
fi

# ── Rollback ──────────────────────────────────────────────────────────────────
if [ "$ROLLBACK" = true ]; then
  CURRENT=$(active_stack)
  PREVIOUS=$(inactive_stack)
  echo "==> Rolling back: $CURRENT → $PREVIOUS"

  docker compose -p "olpdf-$PREVIOUS" -f "$APP_DIR/docker-compose.$PREVIOUS.yml" up -d --remove-orphans

  if ! health_check "$(stack_port "$PREVIOUS")"; then
    echo "ERROR: Previous stack ($PREVIOUS) is not healthy. Manual intervention required."
    exit 1
  fi

  update_nginx "$PREVIOUS"
  echo "$PREVIOUS" > "$STATE_FILE"
  echo "==> Rolled back to $PREVIOUS"
  echo "    Stopping broken stack ($CURRENT)..."
  docker compose -p "olpdf-$CURRENT" -f "$APP_DIR/docker-compose.$CURRENT.yml" stop || true
  exit 0
fi

# ── Preflight ─────────────────────────────────────────────────────────────────
if [ ! -f "$ENV_FILE" ]; then
  echo "ERROR: $ENV_FILE not found."
  echo "       Copy your .env.prod to $ENV_FILE"
  exit 1
fi

if [ ! -d "$REPO_DIR/.git" ]; then
  echo "ERROR: $REPO_DIR not found. Run setup first:"
  echo "       git clone https://github.com/Chidi09/olpdf.git $REPO_DIR"
  exit 1
fi

docker network create olpdf-shared 2>/dev/null || true

# ── Deploy ────────────────────────────────────────────────────────────────────
ACTIVE=$(active_stack)
INACTIVE=$(inactive_stack)
INACTIVE_PORT=$(stack_port "$INACTIVE")

echo ""
echo "============================================"
echo "  OLPDF API Deploy"
echo "  Active:   $ACTIVE  (port: $(stack_port "$ACTIVE"))"
echo "  Building: $INACTIVE (port: $INACTIVE_PORT)"
echo "============================================"

echo ""
echo "==> Pulling latest code"
cd "$REPO_DIR"
git fetch --all --prune
git reset --hard origin/master

echo ""
echo "==> Generating compose files"
cd "$APP_DIR"
generate_compose blue
generate_compose green

echo ""
echo "==> Removing stale image from previous cycle"
docker rmi "olpdf/api:$INACTIVE" 2>/dev/null \
  && echo "    Removed olpdf/api:$INACTIVE" \
  || echo "    No stale image to remove"

echo ""
echo "==> Building Go export-service image"
docker build \
  -t "olpdf/export:latest" \
  -f "$REPO_DIR/apps/export-service/Dockerfile" \
  "$REPO_DIR/apps/export-service"

echo ""
echo "==> Restarting export-service with new image"
docker compose -f "$APP_DIR/docker-compose.infra.yml" up -d --no-deps export

echo ""
echo "==> Building OCR worker image"
docker build \
  -t "olpdf/ocr-worker:latest" \
  -f "$REPO_DIR/apps/ocr-worker/Dockerfile" \
  "$REPO_DIR/apps/ocr-worker"

echo ""
echo "==> Restarting OCR worker with new image"
docker compose -f "$APP_DIR/docker-compose.infra.yml" up -d --no-deps ocr-worker

echo ""
echo "==> Building API image"
docker build \
  -t "olpdf/api:$INACTIVE" \
  -f "$REPO_DIR/apps/api/Dockerfile" \
  "$REPO_DIR/apps/api"

echo ""
echo "==> Starting $INACTIVE stack"
docker compose -p "olpdf-$INACTIVE" -f "$APP_DIR/docker-compose.$INACTIVE.yml" up -d --remove-orphans

echo ""
echo "==> Health checking new stack"
if ! health_check "$INACTIVE_PORT"; then
  echo ""
  echo "ERROR: API failed health check. Aborting."
  echo "Logs:"
  docker compose -p "olpdf-$INACTIVE" -f "$APP_DIR/docker-compose.$INACTIVE.yml" logs --tail=80 api 2>/dev/null || true
  docker compose -p "olpdf-$INACTIVE" -f "$APP_DIR/docker-compose.$INACTIVE.yml" down
  exit 1
fi

echo ""
echo "==> Switching traffic to $INACTIVE"
update_nginx "$INACTIVE"
echo "$INACTIVE" > "$STATE_FILE"

echo ""
echo "==> Stopping old stack ($ACTIVE)"
docker compose -f "$APP_DIR/docker-compose.$ACTIVE.yml" stop || true

echo ""
echo "==> Pruning build cache and dangling images"
docker builder prune -f
docker image prune -f

echo ""
echo "============================================"
echo "  Deploy complete!"
echo "  Active: $INACTIVE"
echo "  API: https://api.olpdf.xyz"
echo "  Rollback: ./deploy.sh --rollback"
echo "============================================"
docker compose -f "$APP_DIR/docker-compose.$INACTIVE.yml" ps

if [ "$TAIL_LOGS" = true ]; then
  echo ""
  echo "==> Tailing logs (Ctrl+C to stop)"
  docker compose -p "olpdf-$INACTIVE" -f "$APP_DIR/docker-compose.$INACTIVE.yml" logs -f
fi
